import type { Metadata } from "next";
import { Toaster } from "sonner";
import AnimatedBackground from "./components/AnimatedBackground";
import AnimatedParticles from "./components/AnimatedParticles";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AnimatedBackground />
        <AnimatedParticles/>
        <Toaster position="top-center" richColors expand={false}/>
        {children}
      </body>
    </html>
  );
}
